### ISSUE TITLE
AOO and EOO for spatial polygons/shapefiles

### ISSUE THREAD

**Issue by jrfep** [red-list-ecosystem/redlistr#11]
Current versions of AOO and EOO functions assume either a raster or a spatial points object, but it gives an error when using polygon data:

> no slot of name "coords" for this object of class "SpatialPolygonsDataFrame"

I would suggest adding options to process spatial polygon data.

**Comment by calvinkflee** [comment]
Yea, the way around it right now is to convert the spatial polygon to a raster, then putting it into the function. Need to add that (or something more elegant) to the package.

**Comment by jrfep** [comment]
I did this for EOO using the function in package rgeos:

> require(rgeos)
> alpine.bogs <- shapefile(sprintf("%s/alpine bogs mainland and tasmania final v2.shp",gisdata.dir))
> alpine.bogs.EOO <- gConvexHull(alpine.bogs)
> getAreaEOO(alpine.bogs.EOO) 

For AOO, I tried this

> grid <- raster(extent(alpine.bogs),res=10000)
> alpine.bogs.AOO <- rasterize(alpine.bogs,grid,getCover=T)

But for this particular shapefile with lots of small polygons, it misses a lot of cells.

So instead, I used this:

> alpine.bogs.AOO <- raster(extent(alpine.bogs),res=10000)
> values(alpine.bogs.AOO)[cellFromXY(alpine.bogs.AOO,coordinates(alpine.bogs))] <- 1
> table(values(alpine.bogs.AOO)) ## The number of AOO cells

This second options actually uses the vertices of the polygon to do the spatial query, but would not allow to estimate the coverage within each cell. 

I think the rasterize option should work if polygons are larger than the grid.

**Comment by calvinkflee** [comment]
I just did some manual testing and confirmed that gConvexHull and chull produces identical results, so I'll add that to the EOO functions so it can take all of spatial points, spatial polygons, and raster.
