### ISSUE TITLE
data for testing

### ISSUE THREAD

**Issue by nick-murray** [red-list-ecosystem/redlistr#3]
There are some small rasters that might be suitable for testing [here](https://figshare.com/articles/Simulated_ecosystem_distributions_from_The_use_of_range_size_to_assess_risks_to_biodiversity_from_stochastic_threats/4648939). These are simulated but georeferenced - we could pick one (say 1127.tiff) and if it's small enough we can provide it in the package. We might also be able to make a suitable dataset using the raster function, just like the raster package does. We could also make a small one from remap, such as the Gulf of Carpentaria mangroves.

**Comment by calvinkflee** [comment]
I've included two tifs (each 450kb) of mangroves around Western Port Bay, Victoria as examples to run for the vignette. Should be good enough for now!
