### ISSUE TITLE
Package with a similar name

### ISSUE THREAD

**Issue by maelle** [red-list-ecosystem/redlistr#6]
Nice package! I was wondering whether it'd make sense for `redlistr` docs (README, vignette?) to mention ['redllist'](https://github.com/ropensci/rredlist) (IUCN Red List API Client)? To avoid potential confusion. I opened a similar issue in `rredlist` repo :-)

**Comment by calvinkflee** [comment]
Thanks for the note. I've taken the lead from rredlist and have added a sentence similar to what they've said!

**Comment by maelle** [comment]
Cool thank you!
